name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=readonly

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test -v ./...

  slide:
    name: Slide
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install reveal-md
        run: npm install -g reveal-md

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: reveal-md --static public/ --static-dirs=slide/img slide/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
