name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  code:
    name: Code
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: nix develop .#ci -c bash {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Nix
        uses: cachix/install-nix-action@v21
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: go test -v ./...

  slides:
    name: Slides
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: nix develop .#ci -c bash {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Nix
        uses: cachix/install-nix-action@v21
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: make build-slides
